### ISSUE TITLE
Feature Request : Security Cyborg Module

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/arc-station-14#35]
## Description
A module with a stun baton that has infinite charge but less stamina damage, an infinite disabler that also does less stamina damage, a pair of lingering handcuffs (so that the borg cant use it as an anything hand), and a holobarrier projector.

We don't have secbots and I want to legally beat someone.

**Comment by TheDoctor1977** [comment]
this should probably have a dedicated chassis

**Comment by TheDoctor1977** [comment]
> I don't think security borgs would be a good addition. Especially with conventional Borg laws and how security is forced to interact with the crew.
> 
> Under law 1 a Borg cannot harm crew or through inaction allow crew to harm.. while YES the trolly problem is to be considered.. batoning or disablering someone is still crew harm.
> 
> Law 2 a Borg must obey orders means that any tider can tell a Borg to beat someone's ass if law 1 didn't apply. And unless said person is More Important and can tell the Borg "Nuh uh" the Borg will usually be forced to do so
> 
> While you could give sec borgs a dedicated lawset.. borgs aren't meant to be combative unless they're syndicate aligned to begin with. And sec borgs would be a prime EMAG target. So.. I don't think it's smart.

these are actually good points

**Comment by bruhmogus** [comment]
> I don't think security borgs would be a good addition. Especially with conventional Borg laws and how security is forced to interact with the crew.
> 
> Under law 1 a Borg cannot harm crew or through inaction allow crew to harm.. while YES the trolly problem is to be considered.. batoning or disablering someone is still crew harm.
> 
> Law 2 a Borg must obey orders means that any tider can tell a Borg to beat someone's ass if law 1 didn't apply. And unless said person is More Important and can tell the Borg "Nuh uh" the Borg will usually be forced to do so
> 
> While you could give sec borgs a dedicated lawset.. borgs aren't meant to be combative unless they're syndicate aligned to begin with. And sec borgs would be a prime EMAG target. So.. I don't think it's smart.

simply give it a lawset that only applies to sec and command, and for emagging shrimply give them a plate that needs to be pried out as well. for the crew harm problem, stun batons when active do not deal damage, and we can just give them a special disabler that doesnt do any burn

**Comment by Creatorbot01** [comment]
Malf ai going to have field day with this

**Comment by Hobbitmax** [comment]
> > I don't think security borgs would be a good addition. Especially with conventional Borg laws and how security is forced to interact with the crew.
> > Under law 1 a Borg cannot harm crew or through inaction allow crew to harm.. while YES the trolly problem is to be considered.. batoning or disablering someone is still crew harm.
> > Law 2 a Borg must obey orders means that any tider can tell a Borg to beat someone's ass if law 1 didn't apply. And unless said person is More Important and can tell the Borg "Nuh uh" the Borg will usually be forced to do so
> > While you could give sec borgs a dedicated lawset.. borgs aren't meant to be combative unless they're syndicate aligned to begin with. And sec borgs would be a prime EMAG target. So.. I don't think it's smart.
> 
> simply give it a lawset that only applies to sec and command, and for emagging shrimply give them a plate that needs to be pried out as well. for the crew harm problem, stun batons when active do not deal damage, and we can just give them a special disabler that doesnt do any burn


This still heavily contradicts standard Borg gameplay (no harming crew) and laws have to be well thought out and specific. If you could give a demonstration of this lawset that would be helpful.


Additionally in the event of ion storm or similar this could heavily effect security borgs and force them to have similar to standard NT lawset. Which may result in a similar conflict.

Additionally. Security borgs can still be manufactured by science. And there's no way to ensure that a security Borg (other than directly checking with diagnostic hud) meaning a rogue syndicate traitor could turn 8 TCs into a Borg army very easily and efficiently 
 Normally this is kept in check by all weapons requiring the traitor to spend TC on them.

Security weapons could presumably be manufactured.
Meaning they'd have to be put in the sec lathe for any modules.
And a Borg still is not meant for combat.

Borgs can't slip. Borgs would have recharging stuns. And handcuffs. Plus borgs are already naturally faster than crew..

Borgs also cannot be stunned with conventional weapondry. Other than flashes.

This all means security borgs can't be dealt with by security via anything less than there pistol or lonfs (flashes merely stun them which can give you free damage with the former)


Overall. I would NOT recommend it being added.

**Comment by bruhmogus** [comment]
> > > I don't think security borgs would be a good addition. Especially with conventional Borg laws and how security is forced to interact with the crew.
> > > Under law 1 a Borg cannot harm crew or through inaction allow crew to harm.. while YES the trolly problem is to be considered.. batoning or disablering someone is still crew harm.
> > > Law 2 a Borg must obey orders means that any tider can tell a Borg to beat someone's ass if law 1 didn't apply. And unless said person is More Important and can tell the Borg "Nuh uh" the Borg will usually be forced to do so
> > > While you could give sec borgs a dedicated lawset.. borgs aren't meant to be combative unless they're syndicate aligned to begin with. And sec borgs would be a prime EMAG target. So.. I don't think it's smart.
> > 
> > 
> > simply give it a lawset that only applies to sec and command, and for emagging shrimply give them a plate that needs to be pried out as well. for the crew harm problem, stun batons when active do not deal damage, and we can just give them a special disabler that doesnt do any burn
> 
> This still heavily contradicts standard Borg gameplay (no harming crew) and laws have to be well thought out and specific. If you could give a demonstration of this lawset that would be helpful.
> 
> Additionally in the event of ion storm or similar this could heavily effect security borgs and force them to have similar to standard NT lawset. Which may result in a similar conflict.
> 
> Additionally. Security borgs can still be manufactured by science. And there's no way to ensure that a security Borg (other than directly checking with diagnostic hud) meaning a rogue syndicate traitor could turn 8 TCs into a Borg army very easily and efficiently Normally this is kept in check by all weapons requiring the traitor to spend TC on them.
> 
> Security weapons could presumably be manufactured. Meaning they'd have to be put in the sec lathe for any modules. And a Borg still is not meant for combat.
> 
> Borgs can't slip. Borgs would have recharging stuns. And handcuffs. Plus borgs are already naturally faster than crew..
> 
> Borgs also cannot be stunned with conventional weapondry. Other than flashes.
> 
> This all means security borgs can't be dealt with by security via anything less than there pistol or lonfs (flashes merely stun them which can give you free damage with the former)
> 
> Overall. I would NOT recommend it being added.

Add the module to secfab, remove the cuffs and force the stuns to draw from battery, and the emag problem was already solved by just giving a different chassis for the module that has high protection, which would also remove ion storm laws

**Comment by Hobbitmax** [comment]
> > > > I don't think security borgs would be a good addition. Especially with conventional Borg laws and how security is forced to interact with the crew.
> > > > Under law 1 a Borg cannot harm crew or through inaction allow crew to harm.. while YES the trolly problem is to be considered.. batoning or disablering someone is still crew harm.
> > > > Law 2 a Borg must obey orders means that any tider can tell a Borg to beat someone's ass if law 1 didn't apply. And unless said person is More Important and can tell the Borg "Nuh uh" the Borg will usually be forced to do so
> > > > While you could give sec borgs a dedicated lawset.. borgs aren't meant to be combative unless they're syndicate aligned to begin with. And sec borgs would be a prime EMAG target. So.. I don't think it's smart.
> > > 
> > > 
> > > simply give it a lawset that only applies to sec and command, and for emagging shrimply give them a plate that needs to be pried out as well. for the crew harm problem, stun batons when active do not deal damage, and we can just give them a special disabler that doesnt do any burn
> > 
> > 
> > This still heavily contradicts standard Borg gameplay (no harming crew) and laws have to be well thought out and specific. If you could give a demonstration of this lawset that would be helpful.
> > Additionally in the event of ion storm or similar this could heavily effect security borgs and force them to have similar to standard NT lawset. Which may result in a similar conflict.
> > Additionally. Security borgs can still be manufactured by science. And there's no way to ensure that a security Borg (other than directly checking with diagnostic hud) meaning a rogue syndicate traitor could turn 8 TCs into a Borg army very easily and efficiently Normally this is kept in check by all weapons requiring the traitor to spend TC on them.
> > Security weapons could presumably be manufactured. Meaning they'd have to be put in the sec lathe for any modules. And a Borg still is not meant for combat.
> > Borgs can't slip. Borgs would have recharging stuns. And handcuffs. Plus borgs are already naturally faster than crew..
> > Borgs also cannot be stunned with conventional weapondry. Other than flashes.
> > This all means security borgs can't be dealt with by security via anything less than there pistol or lonfs (flashes merely stun them which can give you free damage with the former)
> > Overall. I would NOT recommend it being added.
> 
> Add the module to secfab, remove the cuffs and force the stuns to draw from battery, and the emag problem was already solved by just giving a different chassis for the module that has high protection, which would also remove ion storm laws

New chassis does nothing to prevent Borg from being EMAGGED by a scientist giving them a new module (a reasonable request that most borgs would accept)

Drawing from battery is all well and good until science researched the self recharging battery

This also does not solve any of the unfun to fight combat mechanics borgs innately have compared to regular security due to:
Immunity to all forms of slipping.
High natural speed compared to organic crew. (Borgs will outrun you in most situations)
Immunity to dropping weapons.
Immunity to being dealt with in any non destructive method.
Ease of repair (one welder brings em back in the fight if they aren't gibbed.)

**Comment by Guloveos** [comment]
Woah thats a lot of words, I think a "battle borg" could work in the future but not something like this I could add a chassis that cant be emaged for just the battle borg but I dont know how much work that would be.

**Comment by Hobbitmax** [comment]
> Woah thats a lot of words, I think a "battle borg" could work in the future but not something like this I could add a chassis that cant be emaged for just the battle borg but I dont know how much work that would be.

As fun as a battle Borg could be. I still keep my stance that it would not fit well in the game. But that's my opinion. (Yes the syndicate borgs are a exception.)
Although I wouldn't feel that bad if admemes could get special modules for borgs to fight with. Instead of having to EMAG borgs for this.

**Comment by TheDoctor1977** [comment]
doing issue cleanup - closing this because frankly it’s out of scope with the way the server is heading
